name: 🔄 Sync fork with upstream

on:
  schedule:
    - cron: "0 3 * * *" # daily at 3 AM UTC
  workflow_dispatch: # manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "Nogard-YT"
          git config user.email "nogmcpe@gmail.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/misode/misode.github.io.git || true
          git fetch upstream

      - name: Merge upstream/master into fork/master
        run: |
          git checkout master
          git merge upstream/master --no-edit || true
          git push origin master
